// <auto-generated />
using System;
using ApiCatalogo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCatalogo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714184301_UpdateTableVenda")]
    partial class UpdateTableVenda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCatalogo.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            ImagemUrl = "bebidas.jpg",
                            Nome = "Bebidas"
                        },
                        new
                        {
                            CategoriaId = 2,
                            ImagemUrl = "lanches.jpg",
                            Nome = "Lanches"
                        },
                        new
                        {
                            CategoriaId = 3,
                            ImagemUrl = "sobremesas.jpg",
                            Nome = "Sobremesas"
                        });
                });

            modelBuilder.Entity("ApiCatalogo.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Estoque")
                        .HasColumnType("real");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2025, 7, 14, 15, 43, 0, 993, DateTimeKind.Local).AddTicks(3762),
                            Descricao = "Refrigerante 2L",
                            Estoque = 100f,
                            ImagemUrl = "coca.jpg",
                            Nome = "Coca-Cola",
                            Preco = 7.5m
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 2,
                            DataCadastro = new DateTime(2025, 7, 14, 15, 43, 0, 993, DateTimeKind.Local).AddTicks(3769),
                            Descricao = "Pão, carne e queijo",
                            Estoque = 50f,
                            ImagemUrl = "xburguer.jpg",
                            Nome = "X-Burguer",
                            Preco = 15.0m
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 3,
                            DataCadastro = new DateTime(2025, 7, 14, 15, 43, 0, 993, DateTimeKind.Local).AddTicks(3771),
                            Descricao = "1L sabor napolitano",
                            Estoque = 30f,
                            ImagemUrl = "sorvete.jpg",
                            Nome = "Sorvete Napolitano",
                            Preco = 20.0m
                        });
                });

            modelBuilder.Entity("ApiCatalogo.Models.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("ApiCatalogo.Models.Produto", b =>
                {
                    b.HasOne("ApiCatalogo.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCatalogo.Models.Venda", null)
                        .WithMany("Produtos")
                        .HasForeignKey("VendaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ApiCatalogo.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ApiCatalogo.Models.Venda", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
